spring:
  application:
    name: final-project-backend
  
  # 데이터베이스 설정
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  # flyway 마이그레이션 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations:
      - classpath:db/migration
      - classpath:db/seed

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# JWT 설정
jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-and-secure}
  access-expiration: 3600000     # 1시간 (ms)
  refresh-expiration: 604800000  # 7일 (ms)

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /

# 로깅 설정
logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG

ai:
  fastapi:
    url: http://localhost:8000/ #예상경로
    path: /generate-template # 예상경로

