# This workflow will run tests when a pull request is made to feature/AI/base branch

name: Python Build and Test

on:
  pull_request:
    branches: [ feature/AI/base ]
    paths: 
      - 'ai/**'
      - '**.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.py'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install build tools
          python -m pip install build pytest
          # Install project dependencies if they exist
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f ai/requirements.txt ]; then pip install -r ai/requirements.txt; fi

      - name: Build package
        run: |
          # NOTE: put your own distribution build steps here.
          python -m build

      - name: Run tests
        run: |
          # Run pytest if test files exist
          if find . -name "*test*.py" -o -name "test_*.py" | grep -q .; then
            python -m pytest
          else
            echo "No test files found, skipping tests"
          fi